name: BNN
channels:
  - conda-forge
  - defaults
dependencies:
  - python~=3.8.0
  - numpy
  - arviz
  - ipykernel
  - pandas
  - matplotlib
  - seaborn
  - pre-commit
  - black
  - isort
  - mypy
  - pylama
  - jax
  - numpyro
  - pip
  - pip:
      - flax
      - blackjax
      - optax
