name: BNN 
channels:
  - conda-forge
  - defaults
dependencies:
  - python~=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pre-commit
  - black==21.5b2
  - isort==5.9.1
  - mypy
  - pylama
  - jax
  - numpyro
  - pip
    #- pip:
